/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package apl_kasir_abdillah;

import com.sun.glass.events.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.text.SimpleDateFormat;
/**
 *
 * @author ACER
 */
public class formPenjualan2 extends javax.swing.JFrame {
    Connection con;
DefaultTableModel tm;
String tgl;
 public void connect(){
    con=null;
    try{
    Class.forName("com.mysql.jdbc.Driver");
    con=DriverManager.getConnection("jdbc:mysql://127.0.0.1/db_abdillah","root","");
    }catch(Exception e){
    System.out.print("ERROR KUERI KE DATABASE:\n" + e + "\n\n");
    }
    }
    private void tampil_tabel(){
    tm = new DefaultTableModel(null, new Object[]{"ID Penjualan","Tanggal","Total","ID Pelanggan"});
    tabel.setModel(tm);
    tm.getDataVector().removeAllElements();
    try{
    PreparedStatement s = con.prepareStatement("select * from penjualan");
    ResultSet r = s.executeQuery();
    while(r.next()){
    Object[] data = {
    r.getString(1),
    r.getString(2),
    r.getString(3),
    r.getString(4)
    };
    tm.addRow(data);
    }
    }catch(Exception e){
    System.out.print("ERROR KUERI KE DATABASE:\n" + e + "\n\n");
    }
    }
    private void ambilData() {
        try {
            PreparedStatement s = con.prepareStatement("SELECT * FROM pelanggan");
            ResultSet r = s.executeQuery();
            
            while (r.next()) {
            idp.addItem(r.getString("id_pelanggan"));
            }
        }catch (Exception e) {
            
        }
    }
    /**
     * Creates new form formPenjualan2
     */
    public formPenjualan2() {
        initComponents();
        connect();
        tampil_tabel();
        ambilData();
    }
       public void tambah(){
        try{
        PreparedStatement ps = con.prepareStatement("insert into penjualan values(?,?,?,?)");
        ps.setString(1,id.getText());
        ps.setString(2,tgl);
        ps.setString(3,total.getText());
        ps.setString(4,idp.getSelectedItem().toString());
        ps.executeUpdate();
        JOptionPane.showMessageDialog(this, "Transaksi telah ditambahkan");
        tampil_tabel();
        }catch(Exception e){
        System.out.print("ERROR KUERI KE DATABASE:\n" + e + "\n\n");
        }
        }
        public void edit(){
        try{
        PreparedStatement ps = con.prepareStatement("update penjualan set tanggal_penjualan=?, total=?,id_pelanggan=? where id_penjualan=?");
        ps.setString(1,tanggal.getDateFormatString());
        ps.setString(2,total.getText());
        ps.setString(3,idp.getSelectedItem().toString());
        ps.setString(4,id.getText());
        ps.executeUpdate();
        JOptionPane.showMessageDialog(this, "Data berhasil diubah");
        tampil_tabel();
        }catch(Exception e){
        System.out.print("ERROR KUERI KE DATABASE:\n" + e + "\n\n");
        }
        }
        public void hapus(){
        int ok = JOptionPane.showConfirmDialog(null, "Anda yakin akan menghapus transaksi di tanggal " +tanggal.getDateFormatString()+"","Konfirmasi", JOptionPane.YES_NO_CANCEL_OPTION);
        if(ok==0){
        try{
        PreparedStatement ps= con.prepareStatement("delete FROM penjualan where id_penjualan=?");
        ps.setString(1,id.getText());
        ps.executeUpdate();
        JOptionPane.showMessageDialog(this, "Data berhasil dihapus");
        tampil_tabel();
        }catch(Exception e){
        System.out.print("ERROR KUERI KE DATABAE:\n" + e + "\n\n");
        }
        }
        }
        public void klik(){
        int i = tabel.getSelectedRow();
            if(i == -1){
            return;
            }
            String idproduk=(String)tm.getValueAt(i,0);
            id.setText(idproduk);
            String namaBarang=(String)tm.getValueAt(i,1);
            tanggal.setDateFormatString(namaBarang);
            String Harga=(String)tm.getValueAt(i,2);
            total.setText(Harga);
            String Stock = (String) tm.getValueAt(i,3);
            idp.setSelectedItem(Stock);
        }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        tanggal = new com.toedter.calendar.JDateChooser();
        id = new java.awt.TextField();
        button1 = new java.awt.Button();
        button2 = new java.awt.Button();
        button3 = new java.awt.Button();
        button4 = new java.awt.Button();
        total = new java.awt.TextField();
        idp = new javax.swing.JComboBox<>();
        button5 = new java.awt.Button();
        cari = new java.awt.TextField();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("TRANSAKSI");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("ID TRANSAKSI");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("TANGGAL");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("TOTAL");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, -1, -1));

        tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabel);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, -1, 100));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("ID PELANGGAN");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, -1, -1));

        tanggal.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                tanggalPropertyChange(evt);
            }
        });
        jPanel1.add(tanggal, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 100, 150, -1));

        id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idActionPerformed(evt);
            }
        });
        id.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                idKeyTyped(evt);
            }
        });
        jPanel1.add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 60, 80, -1));

        button1.setLabel("SIMPAN");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });
        jPanel1.add(button1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, -1, -1));

        button2.setLabel("UBAH");
        button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button2ActionPerformed(evt);
            }
        });
        jPanel1.add(button2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, -1, -1));

        button3.setLabel("HAPUS");
        button3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button3ActionPerformed(evt);
            }
        });
        jPanel1.add(button3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 240, -1, -1));

        button4.setLabel("BATAL");
        button4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button4ActionPerformed(evt);
            }
        });
        jPanel1.add(button4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 240, -1, -1));
        button4.getAccessibleContext().setAccessibleName("BATAL");

        total.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                totalKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                totalKeyTyped(evt);
            }
        });
        jPanel1.add(total, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 140, 80, -1));

        idp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idpActionPerformed(evt);
            }
        });
        jPanel1.add(idp, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 180, 80, -1));

        button5.setLabel("CARI DATA");
        button5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button5ActionPerformed(evt);
            }
        });
        jPanel1.add(button5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, -1, -1));

        cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cariActionPerformed(evt);
            }
        });
        jPanel1.add(cari, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 280, 270, 20));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 420));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void idpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idpActionPerformed
        // TODO add your handling code here:
        try{
            PreparedStatement ps = con.prepareStatement("select id_pelanggan from pelanggan");
            ps.executeUpdate();
        }catch(Exception e){}
    }//GEN-LAST:event_idpActionPerformed

    private void totalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_totalKeyTyped
        // TODO add your handling code here:
        char karakter = evt.getKeyChar();
        if(!(((karakter >=  '0') && (karakter <= '9' || (karakter == KeyEvent.VK_BACKSPACE) || (karakter == KeyEvent.VK_DELETE))))){
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_totalKeyTyped

    private void totalKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_totalKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_totalKeyReleased

    private void button4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button4ActionPerformed
        // TODO add your handling code here:
        menuUtama2 m = new menuUtama2();
        m.show();
        this.dispose();
    }//GEN-LAST:event_button4ActionPerformed

    private void button3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button3ActionPerformed
        // TODO add your handling code here:
        hapus();
    }//GEN-LAST:event_button3ActionPerformed

    private void button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button2ActionPerformed
        // TODO add your handling code here:
        edit();
    }//GEN-LAST:event_button2ActionPerformed

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        // TODO add your handling code here:
        tambah();
    }//GEN-LAST:event_button1ActionPerformed

    private void idKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idKeyTyped
        // TODO add your handling code here:
        char karakter = evt.getKeyChar();
        if(!(((karakter >=  '0') && (karakter <= '9' || (karakter == KeyEvent.VK_BACKSPACE) || (karakter == KeyEvent.VK_DELETE))))){
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_idKeyTyped

    private void idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idActionPerformed

    private void tanggalPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_tanggalPropertyChange
        // TODO add your handling code here:
        if(tanggal.getDate()!=null){
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            tgl = sdf.format(tanggal.getDate());
        }
    }//GEN-LAST:event_tanggalPropertyChange

    private void tabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelMouseClicked
        // TODO add your handling code here:
        klik();
    }//GEN-LAST:event_tabelMouseClicked

    private void cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cariActionPerformed

    private void button5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button5ActionPerformed
        // TODO add your handling code here:
        tm = new DefaultTableModel (null,
        new Object[] {"id_penjualan","tanggal_penjualan","total","id_pelanggan"});
        tabel.setModel(tm);
        tm.getDataVector().removeAllElements();
        try
        {
         PreparedStatement s = con.prepareStatement("SELECT*FROM penjualan where id_penjualan LIKE '%" + cari.getText().toString() +"%' or tanggal_penjualan LIKE '%" + cari.getText().toString() +"%' or total LIKE '%" + cari.getText().toString() +"%' or id_pelanggan LIKE '%" + cari.getText().toString() +"%'");
         ResultSet r = s.executeQuery();
         while(r.next())
         {
             Object[] data ={
             r.getString(1),
             r.getString(2),
             r.getString(3),
             r.getString(4),
             };
         tm.addRow(data);
         }
         
        }
        catch(Exception e)
        {
        System.out.print("ERROR KUERI KE DATABASE:\n" + e + "\n\n");
        }
    }//GEN-LAST:event_button5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formPenjualan2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formPenjualan2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formPenjualan2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formPenjualan2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formPenjualan2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button button1;
    private java.awt.Button button2;
    private java.awt.Button button3;
    private java.awt.Button button4;
    private java.awt.Button button5;
    private java.awt.TextField cari;
    private java.awt.TextField id;
    private javax.swing.JComboBox<String> idp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabel;
    private com.toedter.calendar.JDateChooser tanggal;
    private java.awt.TextField total;
    // End of variables declaration//GEN-END:variables
}
